version: "3.8"

services:
  config-server:
    container_name: config-server
    image: config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: curl -f http://localhost:8071/news-service/default || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 60s
    environment:
      - CONFIG_SERVER_PORT=8071
      - POSTGRES_PASSWORD=0604
      - POSTGRES_USER=postgres
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/news_portal

  news-server:
    container_name: news-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgresqldb:
        condition: service_started
      config-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_HOST=config-server
      - SPRING_PROFILES_ACTIVE=prod

  postgresqldb:
    container_name: postgresql-db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 0604
      POSTGRES_DB: news_portal

  eureka:
    image: eureka-server
    container_name: eureka
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_started



