locale:
  default: en
  paramName: locale

spring:
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
  application:
    name: news-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQL95Dialect
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: validate
      generate-ddl: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  file:
    path: D:/IdeaProjects/docker_logs/elk_logs.log
  level:
    root: debug

flyway:
  url: ${DATASOURCE_URL}
  locations: /db/migration
  enabled: true
  password: ${POSTGRES_PASSWORD}
  schemas: public
  user: ${POSTGRES_USER}
  encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}/


