jwt:
  secretKey: somewhereOverTheRainbowBlueBirdsFlyAndTheDreamThatYouDareToOhWhyOhWhCan'tI
  validityInMilliSeconds: 86400000
  header: Authorization

locale:
  default: en
  paramName: locale

spring:
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}
  application:
    name: news-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQL95Dialect
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: validate
      generate-ddl: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  file:
    name: D:/IdeaProjects/docker_logs/elk_logs.log
  level:
    root: debug

flyway:
  url: ${DATASOURCE_URL}
  locations: /db/migration
  enabled: true
  password: ${POSTGRES_PASSWORD}
  schemas: public
  user: ${POSTGRES_USER}
  encoding: UTF-8



